# Set the global variables of your website here.
# This includes:
# - Your Name
# - Your Job Title
# - The Introduction on the Homepage

title: Pietro Favaro
email: pietro.favaro@umons.be
description: >- # this means to ignore newlines until "baseurl:"
  FNRS Research Fellow | PhD Student
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://FavaroP.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
# theme: academic-jekyll-theme
plugins:
  - jekyll-feed
