# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Pietro Favaro
email: pietro.favaro@umons.be
description: >- # this means to ignore newlines until "baseurl:"
  FNRS Stipend | PhD Student
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://FavaroP.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: academic-jekyll-theme
plugins:
  - jekyll-feed
