menu:
  - { name: "Publications", url: "/publications" }
  - { name: "Blog", url: "/blog" }
  - { name: "CV", url: "/cv" }
  - { name: "Contact", url: "/contact" }

courses:
  - { name: "Vector Calculus", url: "vector-calculus" }
  - { name: "Quantum Mechanics", url: "quantum-mechanics" }
  - { name: "Stellar Structures", url: "stellar-structures" }

social:
  - { icon: "linkedin", link: "https://www.linkedin.com/in/pietro-favaro/" }
  - { icon: "github", link: "https://github.com/FavaroP" }
  # To add google scholar:
  # - { icon: "google", link: "https://the-google-scholar-webiste.com/"}

contacts:
  - {
      name: "Dr. Academia",
      title: "Professor",
      department: "Physics & Astronomy",
      institution: "Some University",
      institution_address: "1 Main Street, Canada",
      phone: "(000) 000-0000",
      email: "hello@university.edu",
      office: "Science Building 505",
      image: "assets/img/contact.jpg",
    }
